# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-02 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Belt_app', '0002_quotes_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotes',
            name='quoted_by',
        ),
        migrations.AddField(
            model_name='quotes',
            name='quoted_by',
            field=models.ManyToManyField(related_name='quoted_by', to='Belt_app.Users'),
        ),
    ]
